name: private

services:
   inventory-management-laravel-dev:
      container_name: inventory-management-laravel-dev
      hostname: inventory-management-laravel-dev.local
      build:
         context: .
      working_dir: /work
      volumes:
         - ..:/work
         # Volumes for nginx:
         - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      ports:
         - "8000:80"
      command: >
         bash -c "/work/.devcontainer/init.sh && sleep infinity"
      depends_on:
         - inventory-management-laravel-db
      networks:
         private:

   inventory-management-laravel-db:
      image: mysql:8.0-oracle
      container_name: inventory-management-laravel-db
      restart: unless-stopped
      tty: true
      hostname: inventory-management-laravel.local
      environment:
         MYSQL_DATABASE: database
         MYSQL_ROOT_PASSWORD: secret
      ports:
         - "3308:3306"
      volumes:
         - ./mysql:/var/lib/mysql
      networks:
         private:

networks:
   private: